name: os_client
version: 0.1.0
dependencies:
  os_common:
    path: ../os-common
  http: any
  paper_elements: '>=0.4.1 <0.5.0'
  polymer: '>=0.15.0+1 <0.16.0'
dev_dependencies:
  unittest: any
transformers:  
- polymer:
    entry_points:
    - web/index.html
  

