name: os_client
version: 0.1.0
dependencies:
  os_common:
    path: ../os-common
  http: '>=0.11.1+1 <0.12.0'
  paper_elements: '>=0.4.1 <0.5.0'
  polymer: '>=0.15.0+1 <0.16.0'
  stompdart: '>=0.2.2 <0.3.0'
dev_dependencies:
  unittest: '>=0.11.0+5 <0.12.0'
transformers:  
- polymer:
    entry_points:
    - web/index.html
  

