name: os_common
version: 0.1.0
dependencies:
  collection: any
  http: '>=0.11.1+1 <0.12.0'
dev_dependencies:
  redstone: '>=0.5.16 <0.6.0'
  mongo_dart: '>=0.1.44 <0.2.0'
  unittest: '>=0.11.0+5 <0.12.0'

