name: os_snap
version: 0.1.0
dependencies:
  mongo_dart: '>=0.1.44 <0.2.0'
  redstone: '>=0.5.16 <0.6.0'
  os_common:
    path: ../os-common
dev_dependencies:
  unittest: '>=0.11.0+5 <0.12.0'
  os_user:
    path: ../os-user
